modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Stalemated/unrestricted-enchanting/issues"
license = "MIT"

[[mods]]
modId = "unrestricted_enchanting"
version = "${version}"
displayName = "Unrestricted Enchanting"
authors = "Stalemated"
description = '''
A tool that allows you to fully customize enchantment compatibilities!
'''
logoFile = "assets/icon.png"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/unrestricted-enchanting"

[[mixins]]
config = "unrestricted_enchanting.mixins.json"

[[dependencies.unrestricted_enchanting]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.unrestricted_enchanting]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.unrestricted_enchanting]]
modId = "yet_another_config_lib_v3"
mandatory = false
versionRange = "[3.6.6,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.unrestricted_enchanting]]
modId = "s_lib"
mandatory = true
versionRange = "[3.0.1,)"
ordering = "NONE"
side = "BOTH"
