# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.1.0+1.21.1
maven_group = com.stalemated.unrestrictedench
archives_name = unrestricted_enchanting
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.1
yarn_mappings = 1.21.1+build.1

# Dependencies
fabric_loader_version=0.19.2
fabric_api_version=0.116.12+1.21.1
neoforge_version=21.1.231

s_lib_version = 3.0.1+1.21.1
yacl_version = 3.8.2+1.21.1
modmenu_version=11.0.4
yarn_mappings_patch_neoforge_version=1.21+build.6
